version: "3.9"
services:
  app-framework:
    build:
      context: .
      dockerfile: Dockerfile
    # command: /SKILL-UP-SERVER/start-script.sh
    # command: service nginx start
    # command: ls -laF
    command: ./startup-script.sh
    networks:
      - skillup-network
    volumes:
      - $PWD/server:/SKILL-UP-SERVER/server
    ports:
      - 9999:90 # express and exposed docker port are the same
      - 9229:9229 # this is the debug port
    restart: unless-stopped

volumes:
  server:

networks:
  skillup-network:
    external: true

# networks:
#   default:
#     external: true
#     name: skillup-network
